services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - DATABASE_URL=postgresql://aws_user:aws_password@db:5432/aws_ec2
      - S3_BUCKET_NAME=aws-ec2-files-test
      - API_KEY=aws-ec2-api-key
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=aws_ec2
      - POSTGRES_USER=aws_user
      - POSTGRES_PASSWORD=aws_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: